Repository Geo-Mafia/Geo-Mafia, pull requests merged in 2022-11, with the labels that each got.

#16 Adding Player Class Unit Tests
  player_module/player.test.js
  player_module/player_class_declaration.js
Labels: testing

#18 Fe playerdev
  appGeo/src/tests/game_tests.ts
Labels: testing

#32 Wrote up a game components class
  appGeo/src/app/game/game.component.js
  appGeo/src/tests/game_tests.ts
Labels: enhancement

#40 Workflow for iOS App Build
  .github/workflows/main.yml
  appGeo/.gitignore
  appGeo/App_Resources/iOS/GoogleService-Info.plist
  appGeo/App_Resources/iOS/Podfile
  appGeo/App_Resources/iOS/build.xcconfig
  appGeo/package-lock.json
Labels: testing

#70 Fixed the Game Rule Failing Errors
  appGeo/src/app/game/game-rules.component.ts
  appGeo/src/tests/campus-map.spec.ts
  appGeo/src/tests/game.spec.ts
  appGeo/src/tests/game_rules.spec.ts
Labels: enhancement

#80 Barebone working UI chats
  appGeo/src/app/app-routing.module.ts
  appGeo/src/app/app.module.ts
  appGeo/src/app/chat/chat.component.css
  appGeo/src/app/chat/chat.component.html
  appGeo/src/app/chat/chat.component.ts
  appGeo/src/app/chat/chat.module.ts
  appGeo/src/app/home/home-routing.module.ts
  appGeo/src/app/home/home.component.html
  appGeo/src/app/home/home.module.ts
  appGeo/src/app/player/player.component.ts
  appGeo/src/tests/chat.spec.ts
Labels: testing

#81 Have the Killing Players UI working
  appGeo/src/app/home/home-routing.module.ts
  appGeo/src/app/home/home.component.html
  appGeo/src/app/home/home.component.ts
  appGeo/src/app/home/home.module.ts
  appGeo/src/app/player/killing.component.css
  appGeo/src/app/player/killing.component.html
  appGeo/src/app/player/killing.component.ts
  appGeo/src/app/player/killing.module.ts
  appGeo/src/app/player/player.component.ts
Labels: enhancement

#85 UI interface for voting
  appGeo/src/app/home/home-routing.module.ts
  appGeo/src/app/home/home.component.html
  appGeo/src/app/home/home.component.ts
  appGeo/src/app/home/home.module.ts
  appGeo/src/app/player/player.component.ts
  appGeo/src/app/voting/voting.component.css
  appGeo/src/app/voting/voting.component.html
  appGeo/src/app/voting/voting.component.ts
  appGeo/src/app/voting/voting.module.ts
Labels: enhancement

#97 Checking the new workflow which should save a bit more time
  .github/workflows/main.yml
Labels: enhancement

#90 added databaseUpdate
  appGeo/src/app/game/game.component.ts
  appGeo/src/app/home/home.component.ts
  appGeo/src/app/player/player.component.ts
  appGeo/src/main.ts
Labels: enhancement

#103 Game Event Running
  appGeo/src/app/game/game.component.ts
  appGeo/src/app/home/home.component.ts
  appGeo/src/app/player/player.component.ts
Labels: enhancement

#104 Fix to Unit Tests
  appGeo/src/app/player/player.component.ts
  appGeo/src/main.ts
Labels: testing

#110 Unit test errors
  appGeo/src/app/game/game.component.ts
Labels: bug, testing

#115 Code for Location moved over to activate upon Login
  appGeo/src/app/home/home.component.html
  appGeo/src/app/home/home.component.ts
Labels: enhancement
